trigger:
  branches:
    include:
    - main

pool:
  vmImage: 'ubuntu-latest'


variables:
- group: 'k6_variables'

parameters:
  - name: azure_subscription_id
    type: string
    default: $AZURE_SUBSCRIPTION_ID
    displayName: Azure Subscription

  - name: docker_image
    type: string
    default: "sample_app"
    displayName: Name of Docker Image to Build

  - name: resource_group
    type: string
    default: $K6_ACR_RESOURCE_GROUP
    displayName: Resource Group for ACR

  - name: acr_name
    type: string
    default: $K6_ACR
    displayName: Azure Container Registry Name

steps:

  - task: Bash@3
    displayName: Build Image
    inputs:
      targetType: 'inline'
      script: |
        current_utc_date=`date --utc`
        echo $current_utc_date

        echo ----- BUILD IMAGE ------------
        echo $AZURE_SERVICE_CONNECTION
        echo $AZURE_SUBSCRIPTION_ID
        echo $K6_ACR_RESOURCE_GROUP
        echo $K6_ACR
        docker build -t ${{ parameters.docker_image}}:latest -f ./build/Dockerfile . # TODO: confirm Dockerfile location before merge
